###
GET  http://localhost:8000/user/2

###
POST  http://localhost:8000/user
Content-Type: application/json

{
  "username": "Kimberly",
  "password": "kimshy",
  "email": "kimjay@gmail.com",
  "role": "user",
  "image_url": "https://th.bing.com/th?id=OIP.JL2FYRdlJkZl34uduf3h5QHaHa&w=202&h=202&c=7&r=0&o=5&pid=1.7"
}

###
POST  http://localhost:8000/auth/register
Content-Type: application/json

{
  "username": "Tiff",
  "password": "Password1",
  "email": "mwanikitiffany@gmail.com",
  "role": "admin",
  "image_url": "https://th.bing.com/th?id=OIP.JL2FYRdlJkZl34uduf3h5QHaHa&w=202&h=202&c=7&r=0&o=5&pid=1.7"
}

###
POST  http://localhost:8000/auth/login
Content-Type: application/json

{
  "username": "Tiff",
  "password": "Password1"
}

###
POST  http://localhost:8000/auth/login
Content-Type: application/json

{
  "username": "Kimberly",
  "password": "kimshy"
}



###
POST  http://localhost:8000/project
Content-Type: application/json

    {
        "user_id": 1,
        "project_name": "EduPlatform",
        "description": "online education system",
        "githubRepo": "https://github.com/EduTech/EduPlatform_frontend",
        "start_date": "2023-06-01",
        "end_date": "2023-11-01"
    }


###
POST http://localhost:8000/project_id/task
Content-Type: application/json

    {
      "project_id": 1,
      "task_name": "Initialization",
      "description": "Create Repo",
      "due_date": "2024-05-25",
      "completed": false
    }